version: 1.0.{build}
image: Visual Studio 2019

clone_folder: c:\projects\kotirbis

environment:
  JAVA_HOME: C:\Program Files\Java\jdk11
  PATH: C:\Program Files\Java\jdk11;%PATH%

build_script:
- cmd: >-
    cd c:\projects\kotirbis

    mvn --version

    mvn package


artifacts:
- path: target\*.jar
  name: JAR

test: off
